apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{.Values.backend.namespace}}
  name: {{.Values.backend.name}}
  labels:
    app: {{.Values.backend.name}}
spec:
  replicas: {{.Values.backend.replicas}}
  selector:
    matchLabels:
      app: {{.Values.backend.name}}
  template:
    metadata:
      labels:
        app: {{.Values.backend.name}}
    spec:
      containers:
      - name: {{.Values.backend.name}}
        image: {{.Values.backend.image}}
        ports:
        - containerPort: {{.Values.backend.port}}
        env:
        - name: MONGODB_URI
          value: {{.Values.backend.mongouri}}