apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{.Values.pv.name }}
spec:
  claimRef:
    namespace: {{.Values.pvc.namespace}}
    name: {{.Values.pvc.name}}
  capacity:
    storage: {{ .Values.pv.size}}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{.Values.pv.hostPath.path}}
