apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{.Values.pvc.namespace}}
  name: {{.Values.pvc.name}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.size}}