apiVersion: v1
kind: Service
metadata:
  namespace: {{.Values.mongoApp.namespace}}
  name: {{.Values.mongoApp.name}}
  labels:
    app: {{.Values.mongoApp.name}}
spec:
  ports:
  - port: {{.Values.mongoApp.port}}
    targetPort: {{.Values.mongoApp.port}}
  selector:
    app: {{.Values.mongoApp.name}}
  type: ClusterIP